version: '3.1'

services:
  mysql:
    container_name: ghost_mysql
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  ghost:
    container_name: ghost
    image: ghost:1.21.3-alpine
    restart: always
    depends_on: 
      - mysql
    ports:
      - 127.0.0.1:2368:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
