apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: test
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.7
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.2"
              memory: "100M"
            limits:
              cpu: "0.5"
              memory: "500M"
